config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'



  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:create]


  resources :posts, except: [:destroy] do
    
    member do
      post 'vote'
    end
      
    resources :comments, only: [:create] do
      member do
        post 'vote'
      end
    end
  end
    
  resources :categories, only: [:new, :create]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: :true

  after_validation :generate_slug

  
end 

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :post
  has_many :votes, as: :voteable 
  

  validates  :body, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories  
  has_many :votes, as: :voteable 
  

  validates :title, presence: true
  
  
  after_validation :generate_slug

  def total_votes
    self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
 

  def generate_slug
   self.slug= self.title.gsub(" ","-").downcase
  end

  def to_param
    self.slug
  end 
end

##modify

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments
  has_many :votes
  
  has_secure_password validations: false

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: { minimum: 3}

  after_validation :generate_slug

  def admin?
    self.role = "admin"
  end

  def generate_slug
  self.slug = self.username.gsub(" ","-").downcase
  end

  def to_param
  self.slug
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :creator, class_name: 'User', foreign_key: :user_id
    belongs_to :voteable, polymorphic: true
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
helper_method :current_user, :logged_in?  


def current_user
    current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

def logged_in?
    !!current_user
  end  

def require_user
    unless logged_in?
      flash[:error] = "Must be logged in to do that"
      redirect_to root_path
    end  
end    
 
 def access_denied
  flash[:error] = "You cannot do that"
  redirect_to root_path 
 end

 def require_admin
  access_denied unless current_user && current_user.admin?
end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params.require(:category).permit(:name))

    if @category.save
       flash[:notice] = "New category!" 
       redirect_to categories_path
    else
       render :new
    end
  end
end 

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  

  def create
    @post = Post.find_by(slug: params[:post_id])
    @comment = Comment.new(params.require(:comment).permit(:body))
    @comment.post = @post
    @comment.creator = current_user

   if @comment.save
    flash[:notice] = "Your comment has been posted!"
    redirect_to post_path(@post)  
  else
    #handle validations
    render 'posts/show'
    end
  end  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, only: [:new, :create, :edit, :update, :vote]
  before_action :require_creator_or_admin, only: [:edit, :update]

  def index
    @posts = Post.all
 end

def show
    @comment = Comment.new
  end

def new
  @post = Post.new
end

def create
  @post = Post.new(params.require(:post).permit!)
  @post.creator = current_user
  if @post.save
    flash[:notice] = "You've created a post!"
    redirect_to posts_path  
  else
    #handle validations
    render :new
  end  

end

def edit

end

def category
  @category = Category.new
end  

def update
  if @post.update(post_params)
    flash[:notice] = "You updated the post!"
    redirect_to posts_path(@posts)
  else
    render :edit
  end
end 

def vote 
  

Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
  
  respond_to do |format|
    format.html do
      flash[:notice] = "Your vote was counted"
      redirect_to :back
end        
        format.js
    end
end


private

def post_params
  params.require(:post).permit(:url, :title)
end


def set_post
  @post = Post.find_by(slug: params[:id])  
end



def require_creator_or_admin
  access_denied unless logged_in? && (@post.creator == current_user || current_user.admin?) 
end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    #get handle on user (username)
    user = User.find_by(username: params[:username])
    #call authenticate on that user, pass in password
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Welcome, you are now free to move about the cabin"
      redirect_to root_path
    else
      flash[:error] = "Something is wrong with your username or password"
      redirect_to login_path
  end
end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
   

    if @user.save
      flash[:notice] = "You have registered, please login"
      redirect_to login_path
    else
      render :new
    end  
  end    


private

  def users_params
    params.require(:user).permit(:username, :password)
  end  


  def set_post
  @user = User.find_by(slug: params[:id])  
  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(url)
    url.starts_with?('http') ? url : "http://#{url}"
   end 


def display_datetime(dt)
  dt.strftime("%m/%d/%Y %l:%M%P")
  end
end  

app/views/categories/new.html.erb
<h5>Create a Category</h5>

<%= render 'shared/errors', obj: @category %>

  <%= form_for @category do |f| %>
    <%= f.label :name %> 
    <%= f.text_field :name %>
  <br/>
  <%= f.submit "Create Category" %>
<% end %> 

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
  
<% if logged_in? %>
<li>Welcome, <%= current_user.username %></li>
  <li>
    <%= link_to 'New Post', new_post_path %>
  </li>
   <li>
    <%= link_to 'New Category', new_category_path %>
  </li>
  <li><%= link_to 'logout' , logout_path %></li>
<% else %>  
    <li>
       <%= link_to 'Register', register_path %>
    </li>
    <li>
       <%= link_to 'Login', login_path %>
    </li>
  <% end %> 
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render '/shared/errors', obj: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.submit  @post.new_record? ? "Create Post" : "Update Post", class: 'btn' %>
<% end %>    

app/views/posts/edit.html.erb
<h5>Update Post</h5>

<%= render 'form' %>

app/views/posts/index.html.erb
<h3>Welcome to Postit!</h3>




<ul><% @posts.each do |post| %>
 <div class="well"
<li>
    <% if logged_in? %>
    (<%= link_to '<i class="icon-thumbs-up"></i>'.html_safe, vote_post_path(post, vote: true), method: 'post', remote: true %>
    <% end %>
    

    <span id="post_<%=post.id%>_votes"><%= post.total_votes %></span>
    

    <% if logged_in? %>
    <%= link_to '<i class="icon-thumbs-down"></i>'.html_safe, vote_post_path(post, vote: false), method: 'post',remote: true %>)
    <% end %>


    <%= link_to post.title, post_path(post) %>  
    by <%= post.creator.username %>
   <small>[<%=link_to 'link', fix_url(post.url) %>]</small>
    post at <%= display_datetime(post.created_at) %>
    <% if logged_in? %>
    <%= link_to 'Edit', edit_post_path(post) %>
    <% end %>
</li>
</div>
<% end %>
</ul>

app/views/posts/new.html.erb
  <h4>Create a new Post</h4>

  <%= render 'form' %>

app/views/posts/show.html.erb
<h4>You're looking at <%= @post.title %></h4>
<p>URL: <% @post.url %></p>
<p>Description: <%= @post.description %></p>
<div class="well">
<p>
  

  

  <% if logged_in? %>
  <%= render 'shared/errors', obj: @comment %>

  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body %>
    <br/>
    <%= f.submit "Create Comment", class: 'btn btn-primary' %>
  <% end %>  
<% end %>

 <h5>Comments:</h5>
  <ol>
    <% @post.comments.each do |comment| %>
     <li>
    <%= comment.body %> by  <%= comment.creator.username %> </li>
    <% end %>  

  </ol>
</p> 
</div> 

app/views/posts/vote.js.erb
  $("#post_<%=@post.id%>_votes").html("<%=@post.total_votes%>");

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-error span8">
      <h5>Please fix the following errors:</h5>
      <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %> </li>
      <% end %>
      </ul>
    </div>
   </div> 
<% end %>    

app/views/users/new.html.erb
<h5>Register</h5>

<%= render 'shared/errors', obj: @user %>
<%= form_for @user do |f| %>
  <%= f.label :username %> 
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %> 
  <%= f.password_field :password %>
  <br/>
  <%= f.submit "Register", class: 'btn btn-primary' %>
<% end %>